{
  "openapi": "3.0.0",
  "info": {
    "title": "TLU",
    "description": "",
    "version": "1.0.0"
  },
  "paths": {
    "/api/login": {
      "post": {
        "operationId": "login",
        "summary": "User signs in",
        "description": "",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK."
          },
          "401": {
            "description": "unauthorized"
          },
          "422": {
            "description": "bad email or password"
          }
        }
      }
    },
    "/api/signup": {
      "post": {
        "operationId": "signup",
        "summary": "User can register",
        "description": "",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK."
          },
          "401": {
            "description": "unauthorized"
          },
          "422": {
            "description": "bad email or password"
          }
        }
      }
    }
  }
}